modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="http://github.com/McJtyMods/HoloGui/issues"
displayURL="http://github.com/McJtyMods/HoloGui/"
#logoFile="examplemod.png" #optional
#credits="Thanks for this example mod goes to Java" #optional
authors="McJty"

[[mods]]
modId="hologui"
version="${file.jarVersion}"
displayName="HoloGui"
#updateJSONURL="http://myurl.me/" #optional
description='''
Holographic GUI's
'''
[[dependencies.hologui]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.hologui]]
    modId="mcjtylib"
    mandatory=true
    versionRange="[1.16-5.1.2,)"
    ordering="AFTER"
    side="BOTH"
